spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Puede ser 'none', 'update', 'create', 'create-drop' según tus necesidades
    show-sql: true
  # Opcional: Configuración adicional para Hibernate
  hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect